'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';

interface CreativeAsset {
  id: string;
  assetType: string;
  platform: string;
  title?: string;
  assetUrl: string;
  promptUsed?: string;
  provider?: string;
  model?: string;
  dimensions?: string;
  status: string;
  approvalStatus: string;
  slideNumber?: number;
  brandFitScore?: number;
  qualityScore?: number;
  taskId?: string;
  campaignId?: string;
  createdAt: string;
}

const PLATFORM_ICONS: Record<string, string> = {
  Instagram: '📸', TikTok: '🎵', Facebook: '👥', LinkedIn: '💼',
  X: '𝕏', Pinterest: '📌', YouTube: '▶️', general: '🖼️',
};

const STATUS_STYLES: Record<string, string> = {
  draft:    'bg-gray-100 text-gray-600',
  approved: 'bg-green-100 text-green-700',
  rejected: 'bg-red-100 text-red-600',
};

const APPROVAL_STYLES: Record<string, string> = {
  pending:  'bg-amber-100 text-amber-700',
  approved: 'bg-green-100 text-green-700',
  rejected: 'bg-red-100 text-red-600',
};

export default function AssetsPage() {
  const qc = useQueryClient();
  const [platform, setPlatform] = useState('');
  const [status, setStatus]     = useState('');
  const [preview, setPreview]   = useState<CreativeAsset | null>(null);
  const [copied, setCopied]     = useState(false);

  const { data: assets = [], isLoading } = useQuery({
    queryKey: ['lora', 'assets', platform, status],
    queryFn: () =>
      api.get('/lora/assets', { params: { ...(platform ? { platform } : {}), ...(status ? { status } : {}) } })
        .then((r) => r.data as CreativeAsset[]),
    staleTime: 30_000,
  });

  const deleteAsset = useMutation({
    mutationFn: (id: string) => api.delete(`/lora/assets/${id}`),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['lora', 'assets'] }),
  });

  const copyPrompt = async (prompt: string) => {
    await navigator.clipboard.writeText(prompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const platforms = [...new Set(assets.map((a) => a.platform))].filter(Boolean);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Creative Assets</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            {assets.length} asset{assets.length !== 1 ? 's' : ''} generated by Steve
          </p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2 mb-6">
        <FilterBtn label="All platforms" value="" current={platform} onClick={setPlatform} />
        {platforms.map((p) => (
          <FilterBtn key={p} label={`${PLATFORM_ICONS[p] ?? '📱'} ${p}`} value={p} current={platform} onClick={setPlatform} />
        ))}
        <div className="ml-auto flex gap-2">
          <FilterBtn label="All status" value="" current={status} onClick={setStatus} />
          <FilterBtn label="Draft" value="draft" current={status} onClick={setStatus} />
          <FilterBtn label="Approved" value="approved" current={status} onClick={setStatus} />
        </div>
      </div>

      {/* Grid */}
      {isLoading ? (
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
          {[...Array(8)].map((_, i) => (
            <div key={i} className="aspect-square bg-gray-100 rounded-2xl animate-pulse" />
          ))}
        </div>
      ) : assets.length === 0 ? (
        <div className="py-24 text-center">
          <div className="text-5xl mb-4">🎨</div>
          <h2 className="text-base font-semibold text-gray-800 mb-1">No assets yet</h2>
          <p className="text-sm text-gray-500">
            Ask Lora to create images or carousels and Steve will generate them here.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
          {assets.map((asset) => (
            <AssetCard
              key={asset.id}
              asset={asset}
              onPreview={() => setPreview(asset)}
              onDelete={() => deleteAsset.mutate(asset.id)}
            />
          ))}
        </div>
      )}

      {/* Preview Modal */}
      {preview && (
        <div
          className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4"
          onClick={() => setPreview(null)}
        >
          <div
            className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl overflow-hidden"
            onClick={(e) => e.stopPropagation()}
          >
            {preview.assetUrl && (
              <div className="bg-gray-100 flex items-center justify-center p-4">
                <img
                  src={preview.assetUrl}
                  alt={preview.title ?? 'Creative asset'}
                  className="max-h-96 rounded-xl object-contain"
                />
              </div>
            )}
            <div className="p-5">
              <div className="flex items-start justify-between mb-3">
                <div>
                  <h3 className="text-sm font-semibold text-gray-900">
                    {preview.title ?? preview.assetType?.replace(/_/g, ' ')}
                  </h3>
                  <div className="flex items-center gap-2 mt-1 flex-wrap">
                    <span className="text-xs text-gray-500">{PLATFORM_ICONS[preview.platform]} {preview.platform}</span>
                    <span className="text-xs text-gray-400">·</span>
                    <span className="text-xs text-gray-500">{preview.dimensions}</span>
                    {preview.provider && (
                      <>
                        <span className="text-xs text-gray-400">·</span>
                        <span className="text-xs text-gray-500">{preview.provider} / {preview.model}</span>
                      </>
                    )}
                  </div>
                </div>
                <div className="flex gap-2">
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${STATUS_STYLES[preview.status] ?? 'bg-gray-100 text-gray-600'}`}>
                    {preview.status}
                  </span>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${APPROVAL_STYLES[preview.approvalStatus] ?? 'bg-gray-100 text-gray-600'}`}>
                    {preview.approvalStatus}
                  </span>
                </div>
              </div>

              {(preview.qualityScore || preview.brandFitScore) ? (
                <div className="flex gap-3 mb-3">
                  {preview.qualityScore && <ScoreChip label="Quality" score={preview.qualityScore} />}
                  {preview.brandFitScore && <ScoreChip label="Brand fit" score={preview.brandFitScore} />}
                </div>
              ) : null}

              {preview.promptUsed && (
                <div className="bg-gray-50 rounded-xl p-3 mb-4">
                  <div className="text-xs text-gray-400 mb-1">Prompt used</div>
                  <p className="text-xs text-gray-700 leading-relaxed line-clamp-4">{preview.promptUsed}</p>
                </div>
              )}

              <div className="flex gap-3">
                {preview.promptUsed && (
                  <button
                    onClick={() => copyPrompt(preview.promptUsed!)}
                    className="flex-1 text-xs py-2 rounded-xl border border-gray-200 text-gray-600 hover:bg-gray-50"
                  >
                    {copied ? '✓ Copied' : 'Copy prompt'}
                  </button>
                )}
                {preview.assetUrl && (
                  <a
                    href={preview.assetUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex-1 text-center text-xs py-2 rounded-xl bg-violet-600 text-white hover:bg-violet-700"
                  >
                    Download
                  </a>
                )}
                <button
                  onClick={() => setPreview(null)}
                  className="px-4 text-xs py-2 rounded-xl border border-gray-200 text-gray-500 hover:bg-gray-50"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function AssetCard({
  asset,
  onPreview,
  onDelete,
}: {
  asset: CreativeAsset;
  onPreview: () => void;
  onDelete: () => void;
}) {
  return (
    <div className="group relative bg-white rounded-2xl border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
      <button className="w-full aspect-square bg-gray-100 relative overflow-hidden" onClick={onPreview}>
        {asset.assetUrl ? (
          <img
            src={asset.assetUrl}
            alt={asset.title ?? 'Asset'}
            className="w-full h-full object-cover"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center text-4xl text-gray-300">
            🖼️
          </div>
        )}
        {asset.slideNumber && (
          <div className="absolute top-2 left-2 bg-black/60 text-white text-xs px-1.5 py-0.5 rounded-md">
            Slide {asset.slideNumber}
          </div>
        )}
      </button>
      <div className="p-3">
        <div className="flex items-center justify-between mb-1">
          <span className="text-xs text-gray-500 truncate flex-1">
            {PLATFORM_ICONS[asset.platform] ?? '📱'} {asset.platform}
          </span>
          <span className={`text-xs px-1.5 py-0.5 rounded-full font-medium ml-1 flex-shrink-0 ${APPROVAL_STYLES[asset.approvalStatus] ?? 'bg-gray-100 text-gray-500'}`}>
            {asset.approvalStatus}
          </span>
        </div>
        <p className="text-xs text-gray-700 font-medium line-clamp-1">{asset.title ?? asset.assetType?.replace(/_/g, ' ')}</p>
      </div>
      <button
        onClick={onDelete}
        className="absolute top-2 right-2 h-6 w-6 bg-white/90 rounded-full text-gray-400 hover:text-red-500 hidden group-hover:flex items-center justify-center text-xs shadow-sm"
      >
        ×
      </button>
    </div>
  );
}

function FilterBtn({ label, value, current, onClick }: { label: string; value: string; current: string; onClick: (v: string) => void }) {
  return (
    <button
      onClick={() => onClick(value)}
      className={`text-xs px-3 py-1.5 rounded-lg font-medium transition-colors ${
        current === value
          ? 'bg-violet-600 text-white'
          : 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50'
      }`}
    >
      {label}
    </button>
  );
}

function ScoreChip({ label, score }: { label: string; score: number }) {
  const color = score >= 80 ? 'bg-green-100 text-green-700' : score >= 60 ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-600';
  return (
    <div className={`rounded-lg px-3 py-1.5 text-center ${color}`}>
      <div className="text-sm font-bold">{score}</div>
      <div className="text-xs opacity-80">{label}</div>
    </div>
  );
}
